// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(MindChainWalletCoreFFI)
import MindChainWalletCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_noos_wallet_sdk_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_noos_wallet_sdk_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureNoosWalletSdkInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol MobileLightNodeProtocol: AnyObject, Sendable {

    func exportState() throws  -> String

    func observeFinalized(observations: [EndpointStatusObservation]) throws  -> MobileNodeSyncOutcome

    func snapshot() throws  -> MobileNodeSnapshot

}
open class MobileLightNode: MobileLightNodeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_noos_wallet_sdk_fn_clone_mobilelightnode(self.handle, $0) }
    }
public convenience init(chainId: String, genesisHash: String, apiVersion: String, maximumFreshnessMs: UInt64, minimumControlClusterQuorum: UInt8, persistedStateJson: String?)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_constructor_mobilelightnode_new(
        FfiConverterString.lower(chainId),
        FfiConverterString.lower(genesisHash),
        FfiConverterString.lower(apiVersion),
        FfiConverterUInt64.lower(maximumFreshnessMs),
        FfiConverterUInt8.lower(minimumControlClusterQuorum),
        FfiConverterOptionString.lower(persistedStateJson),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_noos_wallet_sdk_fn_free_mobilelightnode(handle, $0) }
    }




open func exportState()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilelightnode_export_state(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func observeFinalized(observations: [EndpointStatusObservation])throws  -> MobileNodeSyncOutcome  {
    return try  FfiConverterTypeMobileNodeSyncOutcome_lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilelightnode_observe_finalized(
            self.uniffiCloneHandle(),
        FfiConverterSequenceTypeEndpointStatusObservation.lower(observations),uniffiCallStatus
    )
})
}

open func snapshot()throws  -> MobileNodeSnapshot  {
    return try  FfiConverterTypeMobileNodeSnapshot_lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilelightnode_snapshot(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileLightNode: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MobileLightNode

    public static func lift(_ handle: UInt64) throws -> MobileLightNode {
        return MobileLightNode(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MobileLightNode) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileLightNode {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MobileLightNode, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileLightNode_lift(_ handle: UInt64) throws -> MobileLightNode {
    return try FfiConverterTypeMobileLightNode.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileLightNode_lower(_ value: MobileLightNode) -> UInt64 {
    return FfiConverterTypeMobileLightNode.lower(value)
}






public protocol MobileWalletCoreProtocol: AnyObject, Sendable {

    func deriveAuthority(seed: Data, purpose: String, suite: UInt32?, account: UInt32, index: UInt32) throws  -> DerivedAuthority

    func reviewTransfer(transactionSpecJson: String, statusJson: String, notesJson: String) throws  -> TransferReview

    func signReviewedTransfer(seed: Data, account: UInt32, index: UInt32, signerScope: UInt8, transactionSpecJson: String, statusJson: String, notesJson: String, expectedReviewId: String) throws  -> SignedTransfer

    func validateSubmissionResponse(expectedTxid: String, responseJson: String) throws  -> SubmissionResult

    func verifyStatus(statusJson: String) throws  -> VerifiedStatus

}
open class MobileWalletCore: MobileWalletCoreProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_noos_wallet_sdk_fn_clone_mobilewalletcore(self.handle, $0) }
    }
public convenience init(chainId: String, genesisHash: String, apiVersion: String, maximumFreshnessMs: UInt64)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_constructor_mobilewalletcore_new(
        FfiConverterString.lower(chainId),
        FfiConverterString.lower(genesisHash),
        FfiConverterString.lower(apiVersion),
        FfiConverterUInt64.lower(maximumFreshnessMs),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_noos_wallet_sdk_fn_free_mobilewalletcore(handle, $0) }
    }




open func deriveAuthority(seed: Data, purpose: String, suite: UInt32?, account: UInt32, index: UInt32)throws  -> DerivedAuthority  {
    return try  FfiConverterTypeDerivedAuthority_lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilewalletcore_derive_authority(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(seed),
        FfiConverterString.lower(purpose),
        FfiConverterOptionUInt32.lower(suite),
        FfiConverterUInt32.lower(account),
        FfiConverterUInt32.lower(index),uniffiCallStatus
    )
})
}

open func reviewTransfer(transactionSpecJson: String, statusJson: String, notesJson: String)throws  -> TransferReview  {
    return try  FfiConverterTypeTransferReview_lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilewalletcore_review_transfer(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(transactionSpecJson),
        FfiConverterString.lower(statusJson),
        FfiConverterString.lower(notesJson),uniffiCallStatus
    )
})
}

open func signReviewedTransfer(seed: Data, account: UInt32, index: UInt32, signerScope: UInt8, transactionSpecJson: String, statusJson: String, notesJson: String, expectedReviewId: String)throws  -> SignedTransfer  {
    return try  FfiConverterTypeSignedTransfer_lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilewalletcore_sign_reviewed_transfer(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(seed),
        FfiConverterUInt32.lower(account),
        FfiConverterUInt32.lower(index),
        FfiConverterUInt8.lower(signerScope),
        FfiConverterString.lower(transactionSpecJson),
        FfiConverterString.lower(statusJson),
        FfiConverterString.lower(notesJson),
        FfiConverterString.lower(expectedReviewId),uniffiCallStatus
    )
})
}

open func validateSubmissionResponse(expectedTxid: String, responseJson: String)throws  -> SubmissionResult  {
    return try  FfiConverterTypeSubmissionResult_lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilewalletcore_validate_submission_response(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(expectedTxid),
        FfiConverterString.lower(responseJson),uniffiCallStatus
    )
})
}

open func verifyStatus(statusJson: String)throws  -> VerifiedStatus  {
    return try  FfiConverterTypeVerifiedStatus_lift(try rustCallWithError(FfiConverterTypeWalletSdkError_lift) {
        uniffiCallStatus in
    uniffi_noos_wallet_sdk_fn_method_mobilewalletcore_verify_status(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(statusJson),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileWalletCore: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MobileWalletCore

    public static func lift(_ handle: UInt64) throws -> MobileWalletCore {
        return MobileWalletCore(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MobileWalletCore) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileWalletCore {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MobileWalletCore, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileWalletCore_lift(_ handle: UInt64) throws -> MobileWalletCore {
    return try FfiConverterTypeMobileWalletCore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileWalletCore_lower(_ value: MobileWalletCore) -> UInt64 {
    return FfiConverterTypeMobileWalletCore.lower(value)
}




public struct AssetAmount: Equatable, Hashable, Codable {
    public let assetId: String
    public let amount: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(assetId: String, amount: String) {
        self.assetId = assetId
        self.amount = amount
    }




}

#if compiler(>=6)
extension AssetAmount: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAssetAmount: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AssetAmount {
        return
            try AssetAmount(
                assetId: FfiConverterString.read(from: &buf),
                amount: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AssetAmount, into buf: inout [UInt8]) {
        FfiConverterString.write(value.assetId, into: &buf)
        FfiConverterString.write(value.amount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetAmount_lift(_ buf: RustBuffer) throws -> AssetAmount {
    return try FfiConverterTypeAssetAmount.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAssetAmount_lower(_ value: AssetAmount) -> RustBuffer {
    return FfiConverterTypeAssetAmount.lower(value)
}


public struct DerivedAuthority: Equatable, Hashable, Codable {
    public let path: [String]
    public let pathBytesHex: String
    public let publicId: String
    public let verifyingKey: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: [String], pathBytesHex: String, publicId: String, verifyingKey: String?) {
        self.path = path
        self.pathBytesHex = pathBytesHex
        self.publicId = publicId
        self.verifyingKey = verifyingKey
    }




}

#if compiler(>=6)
extension DerivedAuthority: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDerivedAuthority: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DerivedAuthority {
        return
            try DerivedAuthority(
                path: FfiConverterSequenceString.read(from: &buf),
                pathBytesHex: FfiConverterString.read(from: &buf),
                publicId: FfiConverterString.read(from: &buf),
                verifyingKey: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: DerivedAuthority, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.path, into: &buf)
        FfiConverterString.write(value.pathBytesHex, into: &buf)
        FfiConverterString.write(value.publicId, into: &buf)
        FfiConverterOptionString.write(value.verifyingKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDerivedAuthority_lift(_ buf: RustBuffer) throws -> DerivedAuthority {
    return try FfiConverterTypeDerivedAuthority.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDerivedAuthority_lower(_ value: DerivedAuthority) -> RustBuffer {
    return FfiConverterTypeDerivedAuthority.lower(value)
}


public struct EndpointStatusObservation: Equatable, Hashable, Codable {
    public let endpointId: String
    public let controlCluster: String
    public let statusJson: String
    /**
     * Hash returned by this endpoint for the node's currently trusted height.
     * It is mandatory when advancing from a non-genesis checkpoint.
     */
    public let ancestorHash: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(endpointId: String, controlCluster: String, statusJson: String,
        /**
         * Hash returned by this endpoint for the node's currently trusted height.
         * It is mandatory when advancing from a non-genesis checkpoint.
         */ancestorHash: String?) {
        self.endpointId = endpointId
        self.controlCluster = controlCluster
        self.statusJson = statusJson
        self.ancestorHash = ancestorHash
    }




}

#if compiler(>=6)
extension EndpointStatusObservation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEndpointStatusObservation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EndpointStatusObservation {
        return
            try EndpointStatusObservation(
                endpointId: FfiConverterString.read(from: &buf),
                controlCluster: FfiConverterString.read(from: &buf),
                statusJson: FfiConverterString.read(from: &buf),
                ancestorHash: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: EndpointStatusObservation, into buf: inout [UInt8]) {
        FfiConverterString.write(value.endpointId, into: &buf)
        FfiConverterString.write(value.controlCluster, into: &buf)
        FfiConverterString.write(value.statusJson, into: &buf)
        FfiConverterOptionString.write(value.ancestorHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEndpointStatusObservation_lift(_ buf: RustBuffer) throws -> EndpointStatusObservation {
    return try FfiConverterTypeEndpointStatusObservation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEndpointStatusObservation_lower(_ value: EndpointStatusObservation) -> RustBuffer {
    return FfiConverterTypeEndpointStatusObservation.lower(value)
}


public struct MobileNodeSnapshot: Equatable, Hashable, Codable {
    public let chainId: String
    public let genesisHash: String
    public let finalizedHeight: UInt64
    public let finalizedHash: String
    public let sequence: UInt64
    public let minimumControlClusterQuorum: UInt8
    public let trustModel: String
    public let retainedCheckpoints: UInt32
    public let stateChecksum: String
    public let requiredAncestorHeight: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chainId: String, genesisHash: String, finalizedHeight: UInt64, finalizedHash: String, sequence: UInt64, minimumControlClusterQuorum: UInt8, trustModel: String, retainedCheckpoints: UInt32, stateChecksum: String, requiredAncestorHeight: UInt64?) {
        self.chainId = chainId
        self.genesisHash = genesisHash
        self.finalizedHeight = finalizedHeight
        self.finalizedHash = finalizedHash
        self.sequence = sequence
        self.minimumControlClusterQuorum = minimumControlClusterQuorum
        self.trustModel = trustModel
        self.retainedCheckpoints = retainedCheckpoints
        self.stateChecksum = stateChecksum
        self.requiredAncestorHeight = requiredAncestorHeight
    }




}

#if compiler(>=6)
extension MobileNodeSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileNodeSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileNodeSnapshot {
        return
            try MobileNodeSnapshot(
                chainId: FfiConverterString.read(from: &buf),
                genesisHash: FfiConverterString.read(from: &buf),
                finalizedHeight: FfiConverterUInt64.read(from: &buf),
                finalizedHash: FfiConverterString.read(from: &buf),
                sequence: FfiConverterUInt64.read(from: &buf),
                minimumControlClusterQuorum: FfiConverterUInt8.read(from: &buf),
                trustModel: FfiConverterString.read(from: &buf),
                retainedCheckpoints: FfiConverterUInt32.read(from: &buf),
                stateChecksum: FfiConverterString.read(from: &buf),
                requiredAncestorHeight: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MobileNodeSnapshot, into buf: inout [UInt8]) {
        FfiConverterString.write(value.chainId, into: &buf)
        FfiConverterString.write(value.genesisHash, into: &buf)
        FfiConverterUInt64.write(value.finalizedHeight, into: &buf)
        FfiConverterString.write(value.finalizedHash, into: &buf)
        FfiConverterUInt64.write(value.sequence, into: &buf)
        FfiConverterUInt8.write(value.minimumControlClusterQuorum, into: &buf)
        FfiConverterString.write(value.trustModel, into: &buf)
        FfiConverterUInt32.write(value.retainedCheckpoints, into: &buf)
        FfiConverterString.write(value.stateChecksum, into: &buf)
        FfiConverterOptionUInt64.write(value.requiredAncestorHeight, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileNodeSnapshot_lift(_ buf: RustBuffer) throws -> MobileNodeSnapshot {
    return try FfiConverterTypeMobileNodeSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileNodeSnapshot_lower(_ value: MobileNodeSnapshot) -> RustBuffer {
    return FfiConverterTypeMobileNodeSnapshot.lower(value)
}


public struct MobileNodeSyncOutcome: Equatable, Hashable, Codable {
    public let advanced: Bool
    public let totalObservations: UInt32
    public let quorumEndpoints: UInt32
    public let quorumControlClusters: UInt32
    public let snapshot: MobileNodeSnapshot
    public let persistedStateJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(advanced: Bool, totalObservations: UInt32, quorumEndpoints: UInt32, quorumControlClusters: UInt32, snapshot: MobileNodeSnapshot, persistedStateJson: String) {
        self.advanced = advanced
        self.totalObservations = totalObservations
        self.quorumEndpoints = quorumEndpoints
        self.quorumControlClusters = quorumControlClusters
        self.snapshot = snapshot
        self.persistedStateJson = persistedStateJson
    }




}

#if compiler(>=6)
extension MobileNodeSyncOutcome: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileNodeSyncOutcome: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileNodeSyncOutcome {
        return
            try MobileNodeSyncOutcome(
                advanced: FfiConverterBool.read(from: &buf),
                totalObservations: FfiConverterUInt32.read(from: &buf),
                quorumEndpoints: FfiConverterUInt32.read(from: &buf),
                quorumControlClusters: FfiConverterUInt32.read(from: &buf),
                snapshot: FfiConverterTypeMobileNodeSnapshot.read(from: &buf),
                persistedStateJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MobileNodeSyncOutcome, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.advanced, into: &buf)
        FfiConverterUInt32.write(value.totalObservations, into: &buf)
        FfiConverterUInt32.write(value.quorumEndpoints, into: &buf)
        FfiConverterUInt32.write(value.quorumControlClusters, into: &buf)
        FfiConverterTypeMobileNodeSnapshot.write(value.snapshot, into: &buf)
        FfiConverterString.write(value.persistedStateJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileNodeSyncOutcome_lift(_ buf: RustBuffer) throws -> MobileNodeSyncOutcome {
    return try FfiConverterTypeMobileNodeSyncOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileNodeSyncOutcome_lower(_ value: MobileNodeSyncOutcome) -> RustBuffer {
    return FfiConverterTypeMobileNodeSyncOutcome.lower(value)
}


public struct OutputReview: Equatable, Hashable, Codable {
    public let assetId: String
    public let amount: String
    public let lockRoot: String
    public let datumRoot: String
    public let birthHeight: UInt64
    public let relativeTimelock: UInt32
    public let memoCommitment: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(assetId: String, amount: String, lockRoot: String, datumRoot: String, birthHeight: UInt64, relativeTimelock: UInt32, memoCommitment: String) {
        self.assetId = assetId
        self.amount = amount
        self.lockRoot = lockRoot
        self.datumRoot = datumRoot
        self.birthHeight = birthHeight
        self.relativeTimelock = relativeTimelock
        self.memoCommitment = memoCommitment
    }




}

#if compiler(>=6)
extension OutputReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOutputReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OutputReview {
        return
            try OutputReview(
                assetId: FfiConverterString.read(from: &buf),
                amount: FfiConverterString.read(from: &buf),
                lockRoot: FfiConverterString.read(from: &buf),
                datumRoot: FfiConverterString.read(from: &buf),
                birthHeight: FfiConverterUInt64.read(from: &buf),
                relativeTimelock: FfiConverterUInt32.read(from: &buf),
                memoCommitment: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: OutputReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.assetId, into: &buf)
        FfiConverterString.write(value.amount, into: &buf)
        FfiConverterString.write(value.lockRoot, into: &buf)
        FfiConverterString.write(value.datumRoot, into: &buf)
        FfiConverterUInt64.write(value.birthHeight, into: &buf)
        FfiConverterUInt32.write(value.relativeTimelock, into: &buf)
        FfiConverterString.write(value.memoCommitment, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOutputReview_lift(_ buf: RustBuffer) throws -> OutputReview {
    return try FfiConverterTypeOutputReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOutputReview_lower(_ value: OutputReview) -> RustBuffer {
    return FfiConverterTypeOutputReview.lower(value)
}


public struct ResourceLimits: Equatable, Hashable, Codable {
    public let bytes: UInt64
    public let grainSteps: UInt64
    public let proofUnits: UInt64
    public let stateReads: UInt64
    public let stateWrites: UInt64
    public let blobBytes: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: UInt64, grainSteps: UInt64, proofUnits: UInt64, stateReads: UInt64, stateWrites: UInt64, blobBytes: UInt64) {
        self.bytes = bytes
        self.grainSteps = grainSteps
        self.proofUnits = proofUnits
        self.stateReads = stateReads
        self.stateWrites = stateWrites
        self.blobBytes = blobBytes
    }




}

#if compiler(>=6)
extension ResourceLimits: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeResourceLimits: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ResourceLimits {
        return
            try ResourceLimits(
                bytes: FfiConverterUInt64.read(from: &buf),
                grainSteps: FfiConverterUInt64.read(from: &buf),
                proofUnits: FfiConverterUInt64.read(from: &buf),
                stateReads: FfiConverterUInt64.read(from: &buf),
                stateWrites: FfiConverterUInt64.read(from: &buf),
                blobBytes: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ResourceLimits, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.bytes, into: &buf)
        FfiConverterUInt64.write(value.grainSteps, into: &buf)
        FfiConverterUInt64.write(value.proofUnits, into: &buf)
        FfiConverterUInt64.write(value.stateReads, into: &buf)
        FfiConverterUInt64.write(value.stateWrites, into: &buf)
        FfiConverterUInt64.write(value.blobBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResourceLimits_lift(_ buf: RustBuffer) throws -> ResourceLimits {
    return try FfiConverterTypeResourceLimits.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeResourceLimits_lower(_ value: ResourceLimits) -> RustBuffer {
    return FfiConverterTypeResourceLimits.lower(value)
}


public struct SignedTransfer: Equatable, Hashable, Codable {
    public let reviewId: String
    public let txid: String
    public let transactionHex: String
    public let witnessesHex: String
    public let submissionJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reviewId: String, txid: String, transactionHex: String, witnessesHex: String, submissionJson: String) {
        self.reviewId = reviewId
        self.txid = txid
        self.transactionHex = transactionHex
        self.witnessesHex = witnessesHex
        self.submissionJson = submissionJson
    }




}

#if compiler(>=6)
extension SignedTransfer: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignedTransfer: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignedTransfer {
        return
            try SignedTransfer(
                reviewId: FfiConverterString.read(from: &buf),
                txid: FfiConverterString.read(from: &buf),
                transactionHex: FfiConverterString.read(from: &buf),
                witnessesHex: FfiConverterString.read(from: &buf),
                submissionJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SignedTransfer, into buf: inout [UInt8]) {
        FfiConverterString.write(value.reviewId, into: &buf)
        FfiConverterString.write(value.txid, into: &buf)
        FfiConverterString.write(value.transactionHex, into: &buf)
        FfiConverterString.write(value.witnessesHex, into: &buf)
        FfiConverterString.write(value.submissionJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignedTransfer_lift(_ buf: RustBuffer) throws -> SignedTransfer {
    return try FfiConverterTypeSignedTransfer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignedTransfer_lower(_ value: SignedTransfer) -> RustBuffer {
    return FfiConverterTypeSignedTransfer.lower(value)
}


public struct SubmissionResult: Equatable, Hashable, Codable {
    public let txid: String
    public let state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(txid: String, state: String) {
        self.txid = txid
        self.state = state
    }




}

#if compiler(>=6)
extension SubmissionResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSubmissionResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SubmissionResult {
        return
            try SubmissionResult(
                txid: FfiConverterString.read(from: &buf),
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SubmissionResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.txid, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSubmissionResult_lift(_ buf: RustBuffer) throws -> SubmissionResult {
    return try FfiConverterTypeSubmissionResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSubmissionResult_lower(_ value: SubmissionResult) -> RustBuffer {
    return FfiConverterTypeSubmissionResult.lower(value)
}


public struct TransferReview: Equatable, Hashable, Codable {
    public let reviewId: String
    public let txid: String
    public let feePayer: String
    public let expiryHeight: UInt64
    public let observedUnsafeHeight: UInt64
    public let observedUnsafeHash: String
    public let observedFinalizedHeight: UInt64
    public let observedFinalizedHash: String
    public let resourceLimits: ResourceLimits
    public let noteInputs: [String]
    public let outputs: [OutputReview]
    public let inputTotals: [AssetAmount]
    public let outputTotals: [AssetAmount]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reviewId: String, txid: String, feePayer: String, expiryHeight: UInt64, observedUnsafeHeight: UInt64, observedUnsafeHash: String, observedFinalizedHeight: UInt64, observedFinalizedHash: String, resourceLimits: ResourceLimits, noteInputs: [String], outputs: [OutputReview], inputTotals: [AssetAmount], outputTotals: [AssetAmount]) {
        self.reviewId = reviewId
        self.txid = txid
        self.feePayer = feePayer
        self.expiryHeight = expiryHeight
        self.observedUnsafeHeight = observedUnsafeHeight
        self.observedUnsafeHash = observedUnsafeHash
        self.observedFinalizedHeight = observedFinalizedHeight
        self.observedFinalizedHash = observedFinalizedHash
        self.resourceLimits = resourceLimits
        self.noteInputs = noteInputs
        self.outputs = outputs
        self.inputTotals = inputTotals
        self.outputTotals = outputTotals
    }




}

#if compiler(>=6)
extension TransferReview: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransferReview: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransferReview {
        return
            try TransferReview(
                reviewId: FfiConverterString.read(from: &buf),
                txid: FfiConverterString.read(from: &buf),
                feePayer: FfiConverterString.read(from: &buf),
                expiryHeight: FfiConverterUInt64.read(from: &buf),
                observedUnsafeHeight: FfiConverterUInt64.read(from: &buf),
                observedUnsafeHash: FfiConverterString.read(from: &buf),
                observedFinalizedHeight: FfiConverterUInt64.read(from: &buf),
                observedFinalizedHash: FfiConverterString.read(from: &buf),
                resourceLimits: FfiConverterTypeResourceLimits.read(from: &buf),
                noteInputs: FfiConverterSequenceString.read(from: &buf),
                outputs: FfiConverterSequenceTypeOutputReview.read(from: &buf),
                inputTotals: FfiConverterSequenceTypeAssetAmount.read(from: &buf),
                outputTotals: FfiConverterSequenceTypeAssetAmount.read(from: &buf)
        )
    }

    public static func write(_ value: TransferReview, into buf: inout [UInt8]) {
        FfiConverterString.write(value.reviewId, into: &buf)
        FfiConverterString.write(value.txid, into: &buf)
        FfiConverterString.write(value.feePayer, into: &buf)
        FfiConverterUInt64.write(value.expiryHeight, into: &buf)
        FfiConverterUInt64.write(value.observedUnsafeHeight, into: &buf)
        FfiConverterString.write(value.observedUnsafeHash, into: &buf)
        FfiConverterUInt64.write(value.observedFinalizedHeight, into: &buf)
        FfiConverterString.write(value.observedFinalizedHash, into: &buf)
        FfiConverterTypeResourceLimits.write(value.resourceLimits, into: &buf)
        FfiConverterSequenceString.write(value.noteInputs, into: &buf)
        FfiConverterSequenceTypeOutputReview.write(value.outputs, into: &buf)
        FfiConverterSequenceTypeAssetAmount.write(value.inputTotals, into: &buf)
        FfiConverterSequenceTypeAssetAmount.write(value.outputTotals, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferReview_lift(_ buf: RustBuffer) throws -> TransferReview {
    return try FfiConverterTypeTransferReview.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransferReview_lower(_ value: TransferReview) -> RustBuffer {
    return FfiConverterTypeTransferReview.lower(value)
}


public struct VerifiedStatus: Equatable, Hashable, Codable {
    public let chainId: String
    public let genesisHash: String
    public let releaseVersion: String
    public let unsafeHeight: UInt64
    public let unsafeHash: String
    public let justifiedHeight: UInt64
    public let justifiedHash: String
    public let finalizedHeight: UInt64
    public let finalizedHash: String
    public let freshnessMs: UInt64
    public let nextOutputBirthHeight: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(chainId: String, genesisHash: String, releaseVersion: String, unsafeHeight: UInt64, unsafeHash: String, justifiedHeight: UInt64, justifiedHash: String, finalizedHeight: UInt64, finalizedHash: String, freshnessMs: UInt64, nextOutputBirthHeight: UInt64) {
        self.chainId = chainId
        self.genesisHash = genesisHash
        self.releaseVersion = releaseVersion
        self.unsafeHeight = unsafeHeight
        self.unsafeHash = unsafeHash
        self.justifiedHeight = justifiedHeight
        self.justifiedHash = justifiedHash
        self.finalizedHeight = finalizedHeight
        self.finalizedHash = finalizedHash
        self.freshnessMs = freshnessMs
        self.nextOutputBirthHeight = nextOutputBirthHeight
    }




}

#if compiler(>=6)
extension VerifiedStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerifiedStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VerifiedStatus {
        return
            try VerifiedStatus(
                chainId: FfiConverterString.read(from: &buf),
                genesisHash: FfiConverterString.read(from: &buf),
                releaseVersion: FfiConverterString.read(from: &buf),
                unsafeHeight: FfiConverterUInt64.read(from: &buf),
                unsafeHash: FfiConverterString.read(from: &buf),
                justifiedHeight: FfiConverterUInt64.read(from: &buf),
                justifiedHash: FfiConverterString.read(from: &buf),
                finalizedHeight: FfiConverterUInt64.read(from: &buf),
                finalizedHash: FfiConverterString.read(from: &buf),
                freshnessMs: FfiConverterUInt64.read(from: &buf),
                nextOutputBirthHeight: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: VerifiedStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.chainId, into: &buf)
        FfiConverterString.write(value.genesisHash, into: &buf)
        FfiConverterString.write(value.releaseVersion, into: &buf)
        FfiConverterUInt64.write(value.unsafeHeight, into: &buf)
        FfiConverterString.write(value.unsafeHash, into: &buf)
        FfiConverterUInt64.write(value.justifiedHeight, into: &buf)
        FfiConverterString.write(value.justifiedHash, into: &buf)
        FfiConverterUInt64.write(value.finalizedHeight, into: &buf)
        FfiConverterString.write(value.finalizedHash, into: &buf)
        FfiConverterUInt64.write(value.freshnessMs, into: &buf)
        FfiConverterUInt64.write(value.nextOutputBirthHeight, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedStatus_lift(_ buf: RustBuffer) throws -> VerifiedStatus {
    return try FfiConverterTypeVerifiedStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedStatus_lower(_ value: VerifiedStatus) -> RustBuffer {
    return FfiConverterTypeVerifiedStatus.lower(value)
}


public
enum WalletSdkError: Swift.Error, Equatable, Hashable, Codable, Foundation.LocalizedError {



    case InvalidProfile
    case InvalidRequest
    case MalformedStatus
    case StaleStatus
    case IndexerUnavailable
    case WrongProtocolIdentity
    case InvalidTransaction
    case InsufficientFunds
    case NonceBoundary
    case FeeBoundary
    case ReviewMismatch
    case SubmissionRejected
    case MalformedSubmitResponse
    case TxidMismatch
    case InvalidObservation
    case InsufficientQuorum
    case CheckpointRegression
    case CheckpointConflict
    case InvalidPersistedState






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension WalletSdkError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletSdkError: FfiConverterRustBuffer {
    typealias SwiftType = WalletSdkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletSdkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .InvalidProfile
        case 2: return .InvalidRequest
        case 3: return .MalformedStatus
        case 4: return .StaleStatus
        case 5: return .IndexerUnavailable
        case 6: return .WrongProtocolIdentity
        case 7: return .InvalidTransaction
        case 8: return .InsufficientFunds
        case 9: return .NonceBoundary
        case 10: return .FeeBoundary
        case 11: return .ReviewMismatch
        case 12: return .SubmissionRejected
        case 13: return .MalformedSubmitResponse
        case 14: return .TxidMismatch
        case 15: return .InvalidObservation
        case 16: return .InsufficientQuorum
        case 17: return .CheckpointRegression
        case 18: return .CheckpointConflict
        case 19: return .InvalidPersistedState

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WalletSdkError, into buf: inout [UInt8]) {
        switch value {





        case .InvalidProfile:
            writeInt(&buf, Int32(1))


        case .InvalidRequest:
            writeInt(&buf, Int32(2))


        case .MalformedStatus:
            writeInt(&buf, Int32(3))


        case .StaleStatus:
            writeInt(&buf, Int32(4))


        case .IndexerUnavailable:
            writeInt(&buf, Int32(5))


        case .WrongProtocolIdentity:
            writeInt(&buf, Int32(6))


        case .InvalidTransaction:
            writeInt(&buf, Int32(7))


        case .InsufficientFunds:
            writeInt(&buf, Int32(8))


        case .NonceBoundary:
            writeInt(&buf, Int32(9))


        case .FeeBoundary:
            writeInt(&buf, Int32(10))


        case .ReviewMismatch:
            writeInt(&buf, Int32(11))


        case .SubmissionRejected:
            writeInt(&buf, Int32(12))


        case .MalformedSubmitResponse:
            writeInt(&buf, Int32(13))


        case .TxidMismatch:
            writeInt(&buf, Int32(14))


        case .InvalidObservation:
            writeInt(&buf, Int32(15))


        case .InsufficientQuorum:
            writeInt(&buf, Int32(16))


        case .CheckpointRegression:
            writeInt(&buf, Int32(17))


        case .CheckpointConflict:
            writeInt(&buf, Int32(18))


        case .InvalidPersistedState:
            writeInt(&buf, Int32(19))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletSdkError_lift(_ buf: RustBuffer) throws -> WalletSdkError {
    return try FfiConverterTypeWalletSdkError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletSdkError_lower(_ value: WalletSdkError) -> RustBuffer {
    return FfiConverterTypeWalletSdkError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAssetAmount: FfiConverterRustBuffer {
    typealias SwiftType = [AssetAmount]

    public static func write(_ value: [AssetAmount], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAssetAmount.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AssetAmount] {
        let len: Int32 = try readInt(&buf)
        var seq = [AssetAmount]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAssetAmount.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEndpointStatusObservation: FfiConverterRustBuffer {
    typealias SwiftType = [EndpointStatusObservation]

    public static func write(_ value: [EndpointStatusObservation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEndpointStatusObservation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EndpointStatusObservation] {
        let len: Int32 = try readInt(&buf)
        var seq = [EndpointStatusObservation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEndpointStatusObservation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeOutputReview: FfiConverterRustBuffer {
    typealias SwiftType = [OutputReview]

    public static func write(_ value: [OutputReview], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeOutputReview.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [OutputReview] {
        let len: Int32 = try readInt(&buf)
        var seq = [OutputReview]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeOutputReview.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_noos_wallet_sdk_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilelightnode_export_state() != 1004) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilelightnode_observe_finalized() != 17780) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilelightnode_snapshot() != 36040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilewalletcore_derive_authority() != 26800) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilewalletcore_review_transfer() != 35068) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilewalletcore_sign_reviewed_transfer() != 18019) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilewalletcore_validate_submission_response() != 19250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_method_mobilewalletcore_verify_status() != 17141) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_constructor_mobilelightnode_new() != 62684) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_noos_wallet_sdk_checksum_constructor_mobilewalletcore_new() != 57686) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureNoosWalletSdkInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
