//! exp2_q64 version-1 constant table for Pulse (GENERATED FILE).
//!
//! GENERATED by `tools/vector-generators/gen_exp2_table.py` — DO NOT EDIT.
//! Regenerate/verify with:
//!     python tools/vector-generators/gen_exp2_table.py --check
//!
//! `EXP2_Q64_TABLE_V1[k] = floor(2^(2^-(k+1)) * 2^64)` for `k = 0..63`:
//! the Q64.64 value of two raised to the k-th fractional-bit weight.
//! Derivation and the exact rounding-order law are frozen in
//! `protocol/spec/pulse-exp2-v1.md`. Table hash (BLAKE3-256 over the
//! 64 entries as u128 LE): `15d783a23bcf9d9e20d1133bbc247a5c94a876705aed5281e73246f67c883999`.

/// `floor(2^(2^-(k+1)) * 2^64)` for `k = 0..63`. Entry 0 is the weight
/// of the most-significant fractional exponent bit (2^-1); entry 63
/// (== 2^64 exactly) the least-significant (2^-64). Every entry is a
/// 65-bit value in `[2^64, 2^65)`, so each multiply step is
/// non-decreasing and the fractional product stays below `2 * T_a`.
pub const EXP2_Q64_TABLE_V1: [u128; 64] = [
    0x16a09e667f3bcc908, // k= 0: floor(2^(2^-1) * 2^64)
    0x1306fe0a31b7152de, // k= 1: floor(2^(2^-2) * 2^64)
    0x1172b83c7d517adcd, // k= 2: floor(2^(2^-3) * 2^64)
    0x10b5586cf9890f629, // k= 3: floor(2^(2^-4) * 2^64)
    0x1059b0d31585743ae, // k= 4: floor(2^(2^-5) * 2^64)
    0x102c9a3e778060ee6, // k= 5: floor(2^(2^-6) * 2^64)
    0x10163da9fb33356d8, // k= 6: floor(2^(2^-7) * 2^64)
    0x100b1afa5abcbed61, // k= 7: floor(2^(2^-8) * 2^64)
    0x10058c86da1c09ea1, // k= 8: floor(2^(2^-9) * 2^64)
    0x1002c605e2e8cec50, // k= 9: floor(2^(2^-10) * 2^64)
    0x100162f3904051fa1, // k=10: floor(2^(2^-11) * 2^64)
    0x1000b175effdc76ba, // k=11: floor(2^(2^-12) * 2^64)
    0x100058ba01fb9f96d, // k=12: floor(2^(2^-13) * 2^64)
    0x10002c5cc37da9491, // k=13: floor(2^(2^-14) * 2^64)
    0x1000162e525ee0547, // k=14: floor(2^(2^-15) * 2^64)
    0x10000b17255775c04, // k=15: floor(2^(2^-16) * 2^64)
    0x1000058b91b5bc9ae, // k=16: floor(2^(2^-17) * 2^64)
    0x100002c5c89d5ec6c, // k=17: floor(2^(2^-18) * 2^64)
    0x10000162e43f4f831, // k=18: floor(2^(2^-19) * 2^64)
    0x100000b1721bcfc99, // k=19: floor(2^(2^-20) * 2^64)
    0x10000058b90cf1e6d, // k=20: floor(2^(2^-21) * 2^64)
    0x1000002c5c863b73f, // k=21: floor(2^(2^-22) * 2^64)
    0x100000162e430e5a1, // k=22: floor(2^(2^-23) * 2^64)
    0x1000000b172183551, // k=23: floor(2^(2^-24) * 2^64)
    0x100000058b90c0b48, // k=24: floor(2^(2^-25) * 2^64)
    0x10000002c5c8601cc, // k=25: floor(2^(2^-26) * 2^64)
    0x1000000162e42fff0, // k=26: floor(2^(2^-27) * 2^64)
    0x10000000b17217fba, // k=27: floor(2^(2^-28) * 2^64)
    0x1000000058b90bfcd, // k=28: floor(2^(2^-29) * 2^64)
    0x100000002c5c85fe3, // k=29: floor(2^(2^-30) * 2^64)
    0x10000000162e42ff0, // k=30: floor(2^(2^-31) * 2^64)
    0x100000000b17217f8, // k=31: floor(2^(2^-32) * 2^64)
    0x10000000058b90bfb, // k=32: floor(2^(2^-33) * 2^64)
    0x1000000002c5c85fd, // k=33: floor(2^(2^-34) * 2^64)
    0x100000000162e42fe, // k=34: floor(2^(2^-35) * 2^64)
    0x1000000000b17217f, // k=35: floor(2^(2^-36) * 2^64)
    0x100000000058b90bf, // k=36: floor(2^(2^-37) * 2^64)
    0x10000000002c5c85f, // k=37: floor(2^(2^-38) * 2^64)
    0x1000000000162e42f, // k=38: floor(2^(2^-39) * 2^64)
    0x10000000000b17217, // k=39: floor(2^(2^-40) * 2^64)
    0x1000000000058b90b, // k=40: floor(2^(2^-41) * 2^64)
    0x100000000002c5c85, // k=41: floor(2^(2^-42) * 2^64)
    0x10000000000162e42, // k=42: floor(2^(2^-43) * 2^64)
    0x100000000000b1721, // k=43: floor(2^(2^-44) * 2^64)
    0x10000000000058b90, // k=44: floor(2^(2^-45) * 2^64)
    0x1000000000002c5c8, // k=45: floor(2^(2^-46) * 2^64)
    0x100000000000162e4, // k=46: floor(2^(2^-47) * 2^64)
    0x1000000000000b172, // k=47: floor(2^(2^-48) * 2^64)
    0x100000000000058b9, // k=48: floor(2^(2^-49) * 2^64)
    0x10000000000002c5c, // k=49: floor(2^(2^-50) * 2^64)
    0x1000000000000162e, // k=50: floor(2^(2^-51) * 2^64)
    0x10000000000000b17, // k=51: floor(2^(2^-52) * 2^64)
    0x1000000000000058b, // k=52: floor(2^(2^-53) * 2^64)
    0x100000000000002c5, // k=53: floor(2^(2^-54) * 2^64)
    0x10000000000000162, // k=54: floor(2^(2^-55) * 2^64)
    0x100000000000000b1, // k=55: floor(2^(2^-56) * 2^64)
    0x10000000000000058, // k=56: floor(2^(2^-57) * 2^64)
    0x1000000000000002c, // k=57: floor(2^(2^-58) * 2^64)
    0x10000000000000016, // k=58: floor(2^(2^-59) * 2^64)
    0x1000000000000000b, // k=59: floor(2^(2^-60) * 2^64)
    0x10000000000000005, // k=60: floor(2^(2^-61) * 2^64)
    0x10000000000000002, // k=61: floor(2^(2^-62) * 2^64)
    0x10000000000000001, // k=62: floor(2^(2^-63) * 2^64)
    0x10000000000000000, // k=63: floor(2^(2^-64) * 2^64)
];
