#!/usr/bin/env python3
"""Run a privacy-claim local implementation test and emit raw immutable evidence.

Dedicated runner for the umbra / private-BESI claim family. IMPLEMENTED rows carry a complete
local contract with falsifier tests; PARTIAL rows run the same crate tests but emit
EXTERNAL_BLOCKED with claim-specific limitations.
"""
from __future__ import annotations

import argparse
from experimental_gate import ROOT, base_continuity, cargo_test, emit

# Audited bindings from claim to the crate(s) implementing its local contract, plus the
# module files that carry it and whether the local state is complete.
CLAIM_BINDINGS = {
    "P1-S-DUAL-ROOT": (("noos-private-besi",), ("crates/noos-private-besi/src/dual_root.rs",), True),
    "P2-S-FUSED-AUDIT": (("noos-private-besi",), ("crates/noos-private-besi/src/fused_audit.rs",), True),
    "P3-S-ALGORITHM-TRANSITION": (("noos-private-besi",), ("crates/noos-private-besi/src/transition_market.rs",), True),
    "P4-S-PAID-DELIVERY": (("noos-private-besi",), ("crates/noos-private-besi/src/delivery.rs",), True),
    "M-3PC-MALICIOUS": (("noos-private-besi",), ("crates/noos-private-besi/src/mpc3.rs",), True),
    "M-HFHE-SUITE": (("noos-private-besi",), ("crates/noos-private-besi/src/hfhe.rs", "crates/noos-private-besi/src/refresh.rs"), False),
    "M-PROOF-CARRYING-REFRESH": (("noos-private-besi",), ("crates/noos-private-besi/src/refresh.rs",), False),
    "M-PRIVACY-DEPTH": (("noos-private-besi",), ("crates/noos-private-besi/src/depth.rs", "crates/noos-private-besi/src/refresh.rs"), True),
    "A-UMBRA-BASE": (("noos-umbra",), ("crates/noos-umbra/src/lib.rs", "crates/noos-umbra/src/stealth.rs"), True),
    "A-UMBRA-HIDDEN": (("noos-umbra",), ("crates/noos-umbra/src/hidden.rs",), True),
    "M-FIBER": (("noos-umbra",), ("crates/noos-umbra/src/fiber_dag.rs",), True),
    "M-BRANCH": (("noos-umbra",), ("crates/noos-umbra/src/branch.rs",), True),
    "S-PRIVACY-IR": (("noos-umbra",), ("crates/noos-umbra/src/privacy_ir.rs",), True),
    "N-TEE-FIBER": (("noos-umbra",), ("crates/noos-umbra/src/tee_fiber.rs", "crates/noos-nel/src/lib.rs"), False),
    "E-NEL-08": (("noos-umbra",), ("crates/noos-umbra/src/tee_fiber.rs", "crates/noos-nel/src/lib.rs"), False),
    "E-NEL-PRIVATE-01": (
        ("noos-private-besi",),
        (
            "crates/noos-private-besi/src/lib.rs",
            "crates/noos-private-besi/src/transformer.rs",
            "crates/noos-private-besi/src/tests.rs",
        ),
        False,
    ),
}

PARTIAL_LIMITATIONS = {
    "M-HFHE-SUITE": (
        "No IND-style model, standard-assumption reduction, independent concrete attack estimate, or production parameters exist.",
        "The exact F_(2^127-1) circuit evaluator is a conformance reference, not encryption or a security claim.",
        "No complete refresh prover or two independent verifier families exist.",
    ),
    "M-PROOF-CARRYING-REFRESH": (
        "The continuity tag is a symmetric audit-key stand-in, not the required zero-knowledge prover.",
        "Only one local verifier family exists; no second independently authored verifier exists.",
        "The exercised ciphertext is a toy Z/(2^64) negative control, not an admitted production suite.",
    ),
    "N-TEE-FIBER": (
        "The hardware quote verifier is an interface; no real vendor TEE, firmware, or specialized hardware evidence is supplied.",
        "The leakage checks use preregistered coarse observations, not public-duration real-hardware timing evidence.",
        "Confidential arbitration and vendor-compromise resistance remain outside the local threat model.",
    ),
    "E-NEL-08": (
        "Attestation mutation, replay, rollback, cross-job, and cross-class behavior is exercised only against a deterministic fixture verifier.",
        "No real TEE prompt timing/length campaign or preregistered hardware leakage budget has run.",
        "No declared confidential-arbitration threshold/adversary has external evidence.",
    ),
    "E-NEL-PRIVATE-01": (
        "The deterministic small transformer conformance path is not the claim-eligible real Qwen2.5-0.5B one-layer run.",
        "Deterministic test sharing is not evidence of fresh OS-CSPRNG sharing or independent non-colluding executors.",
        "The frozen external 25-test lab result and measured time/byte observations are not regenerated by this repository runner.",
    ),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--claim", required=True, choices=sorted(CLAIM_BINDINGS))
    parser.add_argument("--rollback-check", action="store_true")
    args = parser.parse_args()
    packages, modules, implemented = CLAIM_BINDINGS[args.claim]
    test = cargo_test(packages)
    if args.rollback_check:
        continuity = base_continuity()
        if continuity["ordinary_base_live"] is not True or continuity["rollback_verified"] is not True:
            raise SystemExit("ordinary-base rollback continuity failed")
        print("RESULT rollback=PASSED")
        return 0
    sources: list[str] = []
    for package in packages:
        sources.append(f"crates/{package}/Cargo.toml")
    for module in modules:
        if not (ROOT / module).is_file():
            raise SystemExit(f"missing claim module: {module}")
        sources.append(module)
    result = "IMPLEMENTED" if implemented else "EXTERNAL_BLOCKED"
    limitations = ["This is local implementation evidence, not independent or production evidence."]
    if not implemented:
        limitations += PARTIAL_LIMITATIONS[args.claim]
    emit(
        gate="implementation-" + args.claim.lower().replace(".", "-"),
        claims=[args.claim],
        result=result,
        expected=result,
        checks=[{"name": "claim-specific crate tests with falsifiers", "passed": True, "detail": test}],
        sources=sources,
        limitations=limitations,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
