#!/bin/sh
# Generated by deploy/installer_gen.py from deploy/installers/installer.template.
# DO NOT EDIT — regenerate from release/manifest.json.
set -eu
RELEASE_VERSION='0.1.0-dev'
CHANNEL='devnet'
SOURCE_REVISION='3ed1c845520d2245eb331a28c8302a0721c7a2d4'
ARTIFACT_TABLE='noos-transition-go.exe cbd4c74b864519a602cf55c0b0b957ec38504cadb769341c9aa537da70df018e
noos-transition-rust.exe 441f91ff4b21f703e051d90ea34a503b1f98a3b65db86fc3bdd2bf35c399d93a
noos-verify.exe f9c6a4a93087a882d1636d3908c3435a0805bdb167506b9c921f3639b29511ee'
if [ "$#" -ne 2 ]; then
    echo "usage: $0 <source-url-or-dir> <dest-dir>" >&2
    exit 2
fi
SOURCE=$1
DEST=$2
echo "NOOSPHERE installer $RELEASE_VERSION ($CHANNEL, source rev $SOURCE_REVISION)"
STAGE=$(mktemp -d "${TMPDIR:-/tmp}/noos-install-XXXXXX")
trap 'rm -rf "$STAGE"' EXIT
sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d' ' -f1
    else
        shasum -a 256 "$1" | cut -d' ' -f1
    fi
}
COUNT=0
printf '%s\n' "$ARTIFACT_TABLE" | while IFS=' ' read -r NAME EXPECTED; do
    [ -n "$NAME" ] || continue
    TARGET="$STAGE/$NAME"
    case "$SOURCE" in
        http://*|https://*)
            if command -v curl >/dev/null 2>&1; then
                curl -fsSL -o "$TARGET" "${SOURCE%/}/$NAME"
            else
                wget -q -O "$TARGET" "${SOURCE%/}/$NAME"
            fi
            ;;
        *)
            cp "$SOURCE/$NAME" "$TARGET"
            ;;
    esac
    ACTUAL=$(sha256_of "$TARGET")
    if [ "$ACTUAL" != "$EXPECTED" ]; then
        rm -f "$TARGET"
        echo "checksum mismatch for $NAME: expected $EXPECTED got $ACTUAL" >&2
        # Poison the stage so the parent shell refuses to install anything.
        : > "$STAGE/.noos-checksum-failure"
        exit 1
    fi
    echo "verified $NAME"
done
if [ -e "$STAGE/.noos-checksum-failure" ]; then
    echo "aborting: checksum enforcement failed" >&2
    exit 1
fi
mkdir -p "$DEST"
for FILE in "$STAGE"/*; do
    [ -e "$FILE" ] || { echo "empty artifact table" >&2; exit 1; }
    mv "$FILE" "$DEST/$(basename "$FILE")"
    COUNT=$((COUNT + 1))
done
echo "installed $COUNT artifact(s) to $DEST"
exit 0
