#Requires -Version 5.1
# Generated by deploy/installer_gen.py from deploy/installers/installer.template.
# DO NOT EDIT — regenerate from release/manifest.json.
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Source,
    [Parameter(Mandatory = $true)][string]$Dest
)
$ErrorActionPreference = 'Stop'
$ReleaseVersion = '0.1.0-dev'
$Channel = 'devnet'
$SourceRevision = '3ed1c845520d2245eb331a28c8302a0721c7a2d4'
$ArtifactTable = @'
noos-transition-go.exe cbd4c74b864519a602cf55c0b0b957ec38504cadb769341c9aa537da70df018e
noos-transition-rust.exe 441f91ff4b21f703e051d90ea34a503b1f98a3b65db86fc3bdd2bf35c399d93a
noos-verify.exe f9c6a4a93087a882d1636d3908c3435a0805bdb167506b9c921f3639b29511ee
'@
Write-Host "NOOSPHERE installer $ReleaseVersion ($Channel, source rev $SourceRevision)"
$stage = Join-Path ([System.IO.Path]::GetTempPath()) ("noos-install-" + [System.Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $stage | Out-Null
try {
    $rows = $ArtifactTable -split "`r?`n" | Where-Object { $_.Trim() -ne '' }
    if ($rows.Count -eq 0) { throw 'empty artifact table' }
    foreach ($row in $rows) {
        $parts = $row.Trim() -split '\s+', 2
        if ($parts.Count -ne 2) { throw "malformed artifact row: $row" }
        $name = $parts[0]; $expected = $parts[1].ToLowerInvariant()
        $target = Join-Path $stage $name
        if ($Source -match '^https?://') {
            Invoke-WebRequest -Uri ($Source.TrimEnd('/') + '/' + $name) -OutFile $target -UseBasicParsing
        } else {
            Copy-Item -LiteralPath (Join-Path $Source $name) -Destination $target
        }
        $actual = (Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash.ToLowerInvariant()
        if ($actual -ne $expected) {
            Remove-Item -LiteralPath $target -Force
            Write-Error "checksum mismatch for ${name}: expected $expected got $actual" -ErrorAction Continue
            exit 1
        }
        Write-Host "verified $name"
    }
    if (-not (Test-Path -LiteralPath $Dest)) { New-Item -ItemType Directory -Path $Dest | Out-Null }
    foreach ($file in Get-ChildItem -LiteralPath $stage -File) {
        Move-Item -LiteralPath $file.FullName -Destination (Join-Path $Dest $file.Name) -Force
    }
    Write-Host "installed $($rows.Count) artifact(s) to $Dest"
    exit 0
} finally {
    if (Test-Path -LiteralPath $stage) { Remove-Item -LiteralPath $stage -Recurse -Force }
}
