//! Generates the closed `DomainId` registry from the frozen G0 table
//! `protocol/spec/crypto-domains-v1.csv` (plan section 3.3).
//!
//! The CSV is the single source of truth: every hash / signature / HKDF
//! call site must name a generated `DomainId` variant, never a raw string.
//! Registry CI laws enforced here at compile time:
//!   (a) duplicate context strings fail the build;
//!   (b) a context string that is a byte-prefix of another fails the build.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const CSV_RELATIVE: &str = "../../protocol/spec/crypto-domains-v1.csv";

struct Row {
    domain_id: String,
    kind: String,
    context: String,
    consumer: String,
    salt: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed={CSV_RELATIVE}");
    let csv = fs::read_to_string(CSV_RELATIVE)
        .unwrap_or_else(|e| panic!("cannot read {CSV_RELATIVE}: {e}"));

    let rows = parse_rows(&csv);
    enforce_registry_laws(&rows);

    let generated = render(&rows);
    let out_dir = env::var("OUT_DIR").unwrap_or_else(|e| panic!("OUT_DIR unset: {e}"));
    let out_path = Path::new(&out_dir).join("domain_registry.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", out_path.display()));
}

fn parse_rows(csv: &str) -> Vec<Row> {
    let mut rows = Vec::new();
    for line in csv.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') || line.starts_with("domain_id,") {
            continue;
        }
        // The notes column may contain commas; the first five fields never do.
        let mut parts = line.splitn(6, ',');
        let mut next = |what: &str| -> String {
            parts
                .next()
                .unwrap_or_else(|| panic!("registry row missing field `{what}`: {line}"))
                .to_owned()
        };
        let domain_id = next("domain_id");
        let kind = next("kind");
        let context = next("context_string");
        let _algorithm = next("algorithm");
        let consumer = next("consumer");
        let notes = next("notes");

        let salt = if kind == "HKDF_INFO" {
            let (_, rest) = notes
                .split_once("salt=\"")
                .unwrap_or_else(|| panic!("HKDF row {domain_id} has no salt=\"...\" in notes"));
            let end = rest
                .find('"')
                .unwrap_or_else(|| panic!("HKDF row {domain_id}: unterminated salt string"));
            Some(rest[..end].to_owned())
        } else {
            None
        };

        rows.push(Row {
            domain_id,
            kind,
            context,
            consumer,
            salt,
        });
    }
    assert!(!rows.is_empty(), "registry CSV parsed to zero rows");
    rows
}

fn enforce_registry_laws(rows: &[Row]) {
    for (i, a) in rows.iter().enumerate() {
        for (j, b) in rows.iter().enumerate() {
            if i == j {
                continue;
            }
            assert!(
                a.context != b.context,
                "registry law (a) violated: duplicate context `{}`",
                a.context
            );
            assert!(
                !b.context.as_bytes().starts_with(a.context.as_bytes()),
                "registry law (b) violated: `{}` is a byte-prefix of `{}`",
                a.context,
                b.context
            );
            assert!(
                a.domain_id != b.domain_id,
                "duplicate domain_id `{}`",
                a.domain_id
            );
        }
    }
}

fn variant_name(domain_id: &str) -> String {
    let stripped = domain_id
        .strip_prefix("D-")
        .unwrap_or_else(|| panic!("domain_id `{domain_id}` does not start with `D-`"));
    let mut out = String::new();
    for word in stripped.split('-') {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.extend(chars.flat_map(char::to_lowercase));
        }
    }
    out
}

fn kind_variant(kind: &str) -> &'static str {
    match kind {
        "BLAKE3_CONTEXT" => "Blake3Context",
        "BLAKE3_KEYED" => "Blake3Keyed",
        "ED25519_PREFIX" => "Ed25519Prefix",
        "BLS_DST" => "BlsDst",
        "HKDF_INFO" => "HkdfInfo",
        other => panic!("unknown registry kind `{other}`"),
    }
}

fn render(rows: &[Row]) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "// @generated by build.rs from protocol/spec/crypto-domains-v1.csv — DO NOT EDIT.\n"
    );

    let _ = writeln!(
        s,
        "/// Closed registry of every cryptographic domain (one variant per CSV row).\n\
         ///\n\
         /// Generated from the frozen G0 table; adding a domain requires a new\n\
         /// registry row, never an ad-hoc string.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         pub enum DomainId {{"
    );
    for row in rows {
        let _ = writeln!(
            s,
            "    /// `{}` — {} (consumer: {}).\n    {},",
            row.context,
            row.kind,
            row.consumer,
            variant_name(&row.domain_id)
        );
    }
    let _ = writeln!(s, "}}\n");

    let _ = writeln!(
        s,
        "/// Number of registered domains.\npub const DOMAIN_COUNT: usize = {};\n",
        rows.len()
    );

    let _ = writeln!(s, "impl DomainId {{");

    let _ = writeln!(
        s,
        "    /// Every registered domain, in CSV declaration order.\n    pub const ALL: [DomainId; DOMAIN_COUNT] = ["
    );
    for row in rows {
        let _ = writeln!(s, "        DomainId::{},", variant_name(&row.domain_id));
    }
    let _ = writeln!(s, "    ];\n");

    let _ = writeln!(
        s,
        "    /// The `domain_id` column of the registry row.\n    #[must_use]\n    pub const fn registry_id(self) -> &'static str {{\n        match self {{"
    );
    for row in rows {
        let _ = writeln!(
            s,
            "            DomainId::{} => \"{}\",",
            variant_name(&row.domain_id),
            row.domain_id
        );
    }
    let _ = writeln!(s, "        }}\n    }}\n");

    let _ = writeln!(
        s,
        "    /// The exact `context_string` column of the registry row.\n    #[must_use]\n    pub const fn context(self) -> &'static str {{\n        match self {{"
    );
    for row in rows {
        let _ = writeln!(
            s,
            "            DomainId::{} => \"{}\",",
            variant_name(&row.domain_id),
            row.context
        );
    }
    let _ = writeln!(s, "        }}\n    }}\n");

    let _ = writeln!(
        s,
        "    /// The `kind` column of the registry row.\n    #[must_use]\n    pub const fn kind(self) -> crate::domains::DomainKind {{\n        match self {{"
    );
    for row in rows {
        let _ = writeln!(
            s,
            "            DomainId::{} => crate::domains::DomainKind::{},",
            variant_name(&row.domain_id),
            kind_variant(&row.kind)
        );
    }
    let _ = writeln!(s, "        }}\n    }}\n");

    let _ = writeln!(
        s,
        "    /// The fixed HKDF salt for `HKDF_INFO` rows (`None` for every other kind).\n    #[must_use]\n    pub const fn hkdf_salt(self) -> Option<&'static str> {{\n        match self {{"
    );
    for row in rows {
        if let Some(salt) = &row.salt {
            let _ = writeln!(
                s,
                "            DomainId::{} => Some(\"{}\"),",
                variant_name(&row.domain_id),
                salt
            );
        }
    }
    let _ = writeln!(s, "            _ => None,\n        }}\n    }}\n");

    let _ = writeln!(
        s,
        "    /// Reverse lookup from the `domain_id` column.\n    #[must_use]\n    pub fn from_registry_id(id: &str) -> Option<Self> {{\n        match id {{"
    );
    for row in rows {
        let _ = writeln!(
            s,
            "            \"{}\" => Some(DomainId::{}),",
            row.domain_id,
            variant_name(&row.domain_id)
        );
    }
    let _ = writeln!(s, "            _ => None,\n        }}\n    }}");

    let _ = writeln!(s, "}}");
    s
}
