//! Conformance tests over `protocol/vectors/crypto/*.json`.
//!
//! Sources (documented per file in each JSON `description`):
//! * `blake3-official.json` — official BLAKE3 repository test vectors;
//! * `ed25519-rfc8032.json` — RFC 8032 section 7.1;
//! * `hkdf-rfc5869.json` — RFC 5869 appendix A (SHA-256 cases);
//! * `bls12381-ietf.json` — ethereum/bls12-381-tests v0.1.2 for the IETF
//!   ciphersuite `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_`;
//! * `domain-hash.json`, `keyed-domain-hash.json`,
//!   `ed25519-noos-domains.json`, `bls-noos-dst.json`,
//!   `hkdf-noos-domains.json`, `feldman-threshold.json` — NOOS-domain KATs
//!   generated by independent implementations (Python blake3 / cryptography
//!   / py_ecc / pure-Python RFC 5869);
//! * `cross-domain.json` — legacy Ascent-era artifacts that must FAIL
//!   NOOSPHERE verification (old identity strings appear hex-encoded only).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use crate::bls::{aggregate_verify_with_dst, fast_aggregate_verify_with_dst, verify_with_dst};
use crate::ed25519::verify_raw;
use crate::hkdf::hkdf_sha256_raw;
use crate::*;
use serde_json::Value;
use std::path::PathBuf;

/// IETF ciphersuite DST used by the imported standard vectors (test-only;
/// protocol call sites use registered `BLS_DST` rows).
const IETF_POP_DST: &[u8] = b"BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_";

fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("protocol")
        .join("vectors")
        .join("crypto")
}

fn load(name: &str) -> Value {
    let path = vectors_dir().join(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("bad JSON in {name}: {e}"))
}

fn cases(doc: &Value) -> &Vec<Value> {
    doc["cases"].as_array().expect("cases array")
}

fn hexf(case: &Value, field: &str) -> Vec<u8> {
    hex::decode(
        case[field]
            .as_str()
            .unwrap_or_else(|| panic!("missing {field}: {case}")),
    )
    .unwrap_or_else(|e| panic!("bad hex in {field}: {e}"))
}

fn arr<const N: usize>(bytes: &[u8]) -> [u8; N] {
    <[u8; N]>::try_from(bytes).unwrap_or_else(|_| panic!("expected {N} bytes, got {}", bytes.len()))
}

fn domain(case: &Value) -> DomainId {
    let id = case["domain_id"].as_str().expect("domain_id");
    DomainId::from_registry_id(id).unwrap_or_else(|| panic!("unknown domain_id {id}"))
}

fn is_positive(case: &Value) -> bool {
    match case["kind"].as_str().expect("kind") {
        "positive" => true,
        "negative" => false,
        other => panic!("unknown kind {other}"),
    }
}

#[test]
fn blake3_official_vectors() {
    let doc = load("blake3-official.json");
    let key: [u8; 32] = arr(doc["key_ascii"].as_str().expect("key_ascii").as_bytes());
    for case in cases(&doc) {
        let input = hexf(case, "bytes");
        let expected = hexf(case, "hash32");
        let mut hasher = blake3::Hasher::new();
        hasher.update(&input);
        let got = *hasher.finalize().as_bytes();
        if is_positive(case) {
            assert_eq!(got.as_slice(), expected, "{}", case["name"]);
            let keyed_expected = hexf(case, "keyed_hash32");
            let mut keyed = blake3::Hasher::new_keyed(&key);
            keyed.update(&input);
            assert_eq!(
                keyed.finalize().as_bytes().as_slice(),
                keyed_expected,
                "{} keyed",
                case["name"]
            );
        } else {
            assert_ne!(got.as_slice(), expected, "{}", case["name"]);
        }
    }
}

#[test]
fn noos_domain_hash_vectors() {
    let doc = load("domain-hash.json");
    for case in cases(&doc) {
        let payload = hexf(case, "bytes");
        let expected = Hash32::from_bytes(arr(&hexf(case, "hash32")));
        let got = hash_domain(domain(case), &[&payload]).unwrap();
        if is_positive(case) {
            assert_eq!(got, expected, "{}", case["name"]);
        } else {
            assert_ne!(got, expected, "{}", case["name"]);
        }
    }
}

#[test]
fn noos_keyed_domain_hash_vectors() {
    let doc = load("keyed-domain-hash.json");
    for case in cases(&doc) {
        let payload = hexf(case, "bytes");
        let key = Hash32::from_bytes(arr(&hexf(case, "key32")));
        let expected = Hash32::from_bytes(arr(&hexf(case, "hash32")));
        let got = keyed_hash_domain(domain(case), &key, &[&payload]).unwrap();
        if is_positive(case) {
            assert_eq!(got, expected, "{}", case["name"]);
        } else {
            assert_ne!(got, expected, "{}", case["name"]);
        }
    }
}

#[test]
fn ed25519_rfc8032_vectors() {
    let doc = load("ed25519-rfc8032.json");
    for case in cases(&doc) {
        let msg = hexf(case, "bytes");
        let pk = ed25519::PublicKey::from_bytes(arr(&hexf(case, "public_key")));
        let sig = ed25519::Signature::from_bytes(arr(&hexf(case, "signature")));
        if is_positive(case) {
            let kp = ed25519::Keypair::from_seed(arr(&hexf(case, "secret_key")));
            assert_eq!(kp.public_key(), pk, "{} pk derivation", case["name"]);
            assert_eq!(kp.sign_raw(&msg), sig, "{} sign", case["name"]);
            verify_raw(&pk, &msg, &sig).unwrap_or_else(|e| panic!("{}: {e}", case["name"]));
        } else {
            assert!(verify_raw(&pk, &msg, &sig).is_err(), "{}", case["name"]);
        }
    }
}

#[test]
fn ed25519_noos_domain_vectors() {
    let doc = load("ed25519-noos-domains.json");
    for case in cases(&doc) {
        let msg = hexf(case, "bytes");
        let pk = ed25519::PublicKey::from_bytes(arr(&hexf(case, "public_key")));
        let sig = ed25519::Signature::from_bytes(arr(&hexf(case, "signature")));
        let result = verify_domain(domain(case), &pk, &[&msg], &sig);
        if is_positive(case) {
            result.unwrap_or_else(|e| panic!("{}: {e}", case["name"]));
        } else {
            assert!(result.is_err(), "{}", case["name"]);
        }
    }
}

#[test]
fn bls12381_ietf_vectors() {
    let doc = load("bls12381-ietf.json");
    for case in cases(&doc) {
        let name = case["name"].as_str().expect("name");
        let positive = is_positive(case);
        match case["op"].as_str().expect("op") {
            "sign" => {
                let privkey = hexf(case, "privkey");
                let msg = hexf(case, "bytes");
                match BlsSecretKey::from_bytes(arr(&privkey)) {
                    Ok(sk) => {
                        assert!(positive, "{name}: invalid key accepted");
                        let expected = BlsSignature::from_bytes(arr(&hexf(case, "signature")));
                        let got = sk.sign_with_dst(&msg, IETF_POP_DST);
                        assert_eq!(got, expected, "{name}");
                        verify_with_dst(&sk.public_key(), &msg, &got, IETF_POP_DST)
                            .unwrap_or_else(|e| panic!("{name}: {e}"));
                    }
                    Err(_) => assert!(!positive, "{name}: valid key rejected"),
                }
            }
            "verify" => {
                let pk = BlsPublicKey::from_bytes(arr(&hexf(case, "pubkey")));
                let sig = BlsSignature::from_bytes(arr(&hexf(case, "signature")));
                let msg = hexf(case, "bytes");
                let result = verify_with_dst(&pk, &msg, &sig, IETF_POP_DST);
                assert_eq!(result.is_ok(), positive, "{name}: {result:?}");
            }
            "aggregate" => {
                let sigs: Vec<BlsSignature> = case["signatures"]
                    .as_array()
                    .expect("signatures")
                    .iter()
                    .map(|s| {
                        BlsSignature::from_bytes(arr(
                            &hex::decode(s.as_str().expect("sig hex")).expect("hex")
                        ))
                    })
                    .collect();
                match bls_aggregate(&sigs) {
                    Ok(agg) => {
                        assert!(positive, "{name}: aggregate accepted");
                        let expected = BlsSignature::from_bytes(arr(&hexf(case, "aggregate")));
                        assert_eq!(agg, expected, "{name}");
                    }
                    Err(_) => assert!(!positive, "{name}: aggregate rejected"),
                }
            }
            "aggregate_verify" => {
                let pks: Vec<BlsPublicKey> = case["pubkeys"]
                    .as_array()
                    .expect("pubkeys")
                    .iter()
                    .map(|p| {
                        BlsPublicKey::from_bytes(arr(
                            &hex::decode(p.as_str().expect("pk hex")).expect("hex")
                        ))
                    })
                    .collect();
                let msgs: Vec<Vec<u8>> = case["messages"]
                    .as_array()
                    .expect("messages")
                    .iter()
                    .map(|m| hex::decode(m.as_str().expect("msg hex")).expect("hex"))
                    .collect();
                let msg_refs: Vec<&[u8]> = msgs.iter().map(Vec::as_slice).collect();
                let sig_bytes = hexf(case, "signature");
                if sig_bytes.len() != 96 {
                    // Truncated wire signature: rejected before parsing.
                    assert!(!positive, "{name}: truncated signature marked positive");
                    continue;
                }
                let sig = BlsSignature::from_bytes(arr(&sig_bytes));
                let result = aggregate_verify_with_dst(&pks, &msg_refs, &sig, IETF_POP_DST);
                assert_eq!(result.is_ok(), positive, "{name}: {result:?}");
            }
            "fast_aggregate_verify" => {
                let pks: Vec<BlsPublicKey> = case["pubkeys"]
                    .as_array()
                    .expect("pubkeys")
                    .iter()
                    .map(|p| {
                        BlsPublicKey::from_bytes(arr(
                            &hex::decode(p.as_str().expect("pk hex")).expect("hex")
                        ))
                    })
                    .collect();
                let msg = hexf(case, "bytes");
                let sig = BlsSignature::from_bytes(arr(&hexf(case, "signature")));
                let result = fast_aggregate_verify_with_dst(&pks, &msg, &sig, IETF_POP_DST);
                assert_eq!(result.is_ok(), positive, "{name}: {result:?}");
            }
            "deserialize_pubkey" => {
                let bytes = hexf(case, "bytes");
                let ok =
                    bytes.len() == 48 && BlsPublicKey::from_bytes(arr(&bytes)).validate().is_ok();
                assert_eq!(ok, positive, "{name}");
            }
            "deserialize_signature" => {
                let bytes = hexf(case, "bytes");
                let ok =
                    bytes.len() == 96 && BlsSignature::from_bytes(arr(&bytes)).validate().is_ok();
                assert_eq!(ok, positive, "{name}");
            }
            other => panic!("unknown op {other}"),
        }
    }
}

#[test]
fn bls_noos_dst_vectors() {
    let doc = load("bls-noos-dst.json");
    for case in cases(&doc) {
        let pk = BlsPublicKey::from_bytes(arr(&hexf(case, "public_key")));
        let sig = BlsSignature::from_bytes(arr(&hexf(case, "signature")));
        let msg = hexf(case, "bytes");
        let result = bls_verify(domain(case), &pk, &msg, &sig);
        if is_positive(case) {
            result.unwrap_or_else(|e| panic!("{}: {e}", case["name"]));
        } else {
            assert!(result.is_err(), "{}", case["name"]);
        }
    }
}

#[test]
fn feldman_threshold_vectors() {
    let doc = load("feldman-threshold.json");
    let threshold = u16::try_from(doc["threshold"].as_u64().expect("threshold")).unwrap();
    let commitments_all: Vec<Vec<BlsPublicKey>> = doc["commitments"]
        .as_array()
        .expect("commitments")
        .iter()
        .map(|v| {
            v.as_array()
                .expect("commitment vector")
                .iter()
                .map(|c| {
                    BlsPublicKey::from_bytes(arr(
                        &hex::decode(c.as_str().expect("hex")).expect("hex")
                    ))
                })
                .collect()
        })
        .collect();
    let group_pk = BlsPublicKey::from_bytes(arr(&hex::decode(
        doc["group_public_key"].as_str().unwrap(),
    )
    .expect("hex")));
    assert_eq!(
        feldman_group_public_key(&commitments_all).unwrap(),
        group_pk
    );

    for case in cases(&doc) {
        let name = case["name"].as_str().expect("name");
        let positive = is_positive(case);
        if name.starts_with("share-") {
            let index = u16::try_from(case["share_index"].as_u64().expect("index")).unwrap();
            let expected = BlsPublicKey::from_bytes(arr(&hexf(case, "share_public_key")));
            match derive_share_public_key(&commitments_all, index) {
                Ok(got) => {
                    assert_eq!(got == expected, positive, "{name}");
                }
                Err(e) => {
                    assert!(!positive, "{name}: {e}");
                    assert_eq!(e, BlsError::InvalidShareIndex, "{name}");
                }
            }
        } else if name.starts_with("partial-sig-") {
            let share_pk = BlsPublicKey::from_bytes(arr(&hexf(case, "share_public_key")));
            let sig = BlsSignature::from_bytes(arr(&hexf(case, "signature")));
            let msg = hexf(case, "bytes");
            let result = bls_verify(domain(case), &share_pk, &msg, &sig);
            assert_eq!(result.is_ok(), positive, "{name}: {result:?}");
        } else if name.starts_with("combine-") {
            let indices: Vec<u16> = case["share_indices"]
                .as_array()
                .expect("share_indices")
                .iter()
                .map(|v| u16::try_from(v.as_u64().expect("index")).unwrap())
                .collect();
            let partials: Vec<BlsSignature> = case["partials"]
                .as_array()
                .expect("partials")
                .iter()
                .map(|s| {
                    BlsSignature::from_bytes(arr(
                        &hex::decode(s.as_str().expect("hex")).expect("hex")
                    ))
                })
                .collect();
            let entries: Vec<(u16, &BlsSignature)> =
                indices.iter().copied().zip(partials.iter()).collect();
            match bls_threshold_combine(&entries, threshold) {
                Ok(combined) => {
                    assert!(positive, "{name}: combine accepted");
                    let expected = BlsSignature::from_bytes(arr(&hexf(case, "combined_signature")));
                    assert_eq!(combined, expected, "{name}");
                    let msg = hexf(case, "bytes");
                    bls_verify(domain(case), &group_pk, &msg, &combined)
                        .unwrap_or_else(|e| panic!("{name}: group verify: {e}"));
                }
                Err(e) => assert!(!positive, "{name}: {e}"),
            }
        } else {
            panic!("unrecognized case {name}");
        }
    }
}

#[test]
fn hkdf_rfc5869_vectors() {
    let doc = load("hkdf-rfc5869.json");
    for case in cases(&doc) {
        let ikm = hexf(case, "bytes");
        let salt = hexf(case, "salt");
        let info = hexf(case, "info");
        let expected = hexf(case, "okm");
        let length = usize::try_from(case["length"].as_u64().expect("length")).unwrap();
        let mut okm = vec![0_u8; length];
        hkdf_sha256_raw(&salt, &ikm, &info, &mut okm).unwrap();
        if is_positive(case) {
            assert_eq!(okm, expected, "{}", case["name"]);
        } else {
            assert_ne!(okm, expected, "{}", case["name"]);
        }
    }
}

#[test]
fn hkdf_noos_domain_vectors() {
    let doc = load("hkdf-noos-domains.json");
    for case in cases(&doc) {
        let ikm = hexf(case, "bytes");
        let suffix = hexf(case, "info_suffix");
        let expected = hexf(case, "okm32");
        let dom = domain(case);
        // The vector's salt column must match the registry row exactly.
        assert_eq!(
            case["salt"].as_str().expect("salt"),
            dom.hkdf_salt().expect("registry salt"),
            "{}",
            case["name"]
        );
        let got = hkdf_derive(dom, &ikm, &[&suffix]).unwrap();
        if is_positive(case) {
            assert_eq!(got.as_slice(), expected, "{}", case["name"]);
        } else {
            assert_ne!(got.as_slice(), expected, "{}", case["name"]);
        }
    }
}

/// Legacy Ascent-era artifacts must fail NOOSPHERE verification
/// (cross-domain rejection law, plan section 3.3).
#[test]
fn cross_domain_rejection_vectors() {
    let doc = load("cross-domain.json");
    for case in cases(&doc) {
        let name = case["name"].as_str().expect("name");
        assert!(
            !is_positive(case),
            "{name}: cross-domain cases are negative"
        );
        let msg = hexf(case, "bytes");

        if case.get("old_hash32").is_some() {
            // Reproduce the legacy keyed construction from its hex-encoded
            // identity strings, prove we faithfully rebuilt it, then prove
            // the NOOS domain hash differs.
            let old_context = String::from_utf8(hexf(case, "old_context_hex")).unwrap();
            let old_key_material = hexf(case, "old_key_material_hex");
            let old_key = blake3::derive_key(&old_context, &old_key_material);
            let mut hasher = blake3::Hasher::new_keyed(&old_key);
            hasher.update(&msg);
            let rebuilt_old = *hasher.finalize().as_bytes();
            assert_eq!(
                rebuilt_old.as_slice(),
                hexf(case, "old_hash32"),
                "{name}: legacy construction mismatch"
            );
            let noos = hash_domain(domain(case), &[&msg]).unwrap();
            assert_eq!(
                noos.as_bytes().as_slice(),
                hexf(case, "noos_hash32"),
                "{name}: NOOS digest mismatch"
            );
            assert_ne!(noos.as_bytes().as_slice(), rebuilt_old.as_slice(), "{name}");
            continue;
        }

        let signature = hexf(case, "signature");
        match signature.len() {
            96 => {
                let pk = BlsPublicKey::from_bytes(arr(&hexf(case, "public_key")));
                let sig = BlsSignature::from_bytes(arr(&signature));
                // Must fail under the named domain AND under every
                // registered BLS DST.
                for dom in DomainId::ALL {
                    if dom.kind() != DomainKind::BlsDst {
                        continue;
                    }
                    assert!(
                        bls_verify(dom, &pk, &msg, &sig).is_err(),
                        "{name}: verified under {}",
                        dom.registry_id()
                    );
                }
                // Sanity: the artifact does verify under its legacy DST,
                // proving the failure is domain separation, not corruption.
                let old_dst = hexf(case, "old_dst_hex");
                verify_with_dst(&pk, &msg, &sig, &old_dst)
                    .unwrap_or_else(|e| panic!("{name}: legacy artifact malformed: {e}"));
            }
            64 => {
                let pk = ed25519::PublicKey::from_bytes(arr(&hexf(case, "public_key")));
                let sig = ed25519::Signature::from_bytes(arr(&signature));
                for dom in DomainId::ALL {
                    if dom.kind() != DomainKind::Ed25519Prefix {
                        continue;
                    }
                    assert!(
                        verify_domain(dom, &pk, &[&msg], &sig).is_err(),
                        "{name}: verified under {}",
                        dom.registry_id()
                    );
                }
                // Sanity: valid under its legacy construction.
                let legacy_msg = match case.get("old_prefix_hex") {
                    Some(_) => {
                        let mut m = hexf(case, "old_prefix_hex");
                        m.extend_from_slice(&msg);
                        m
                    }
                    None => msg.clone(),
                };
                verify_raw(&pk, &legacy_msg, &sig)
                    .unwrap_or_else(|e| panic!("{name}: legacy artifact malformed: {e}"));
            }
            other => panic!("{name}: unexpected signature length {other}"),
        }
    }
}
