#!/usr/bin/env python3
"""gen_exp2_table.py — exp2_q64 version-1 constant table generator.

Emits `crates/noos-ground/src/exp2_table.rs`: the 64-entry Q64.64 table

    EXP2_Q64_TABLE_V1[k] = floor( 2^(2^-(k+1)) * 2^64 ),   k = 0..63

used by Pulse v1 (ch01 section 4.3: "Consensus evaluates the exponent in
signed Q64.64 fixed point, multiplies through the version-1 exp2_q64
constant table ... and rounds toward negative infinity").
`constants-v1.toml [pulse].exp2_q64_table` marks the table UNRESOLVED_SOURCE:
it is a protocol-package artifact that must be generated and frozen; this
script is that generator. Derivation + rounding law documented in
`protocol/spec/pulse-exp2-v1.md`.

Method (exact integer arithmetic only — no floats anywhere):

  * `math.isqrt` gives the exact floor integer square root.
  * s_1 = isqrt(2^(2P+1)) = floor(2^(1/2) * 2^P) exactly, at working
    precision P = 256 fractional bits (192 guard bits over Q64.64).
  * s_{j+1} = isqrt(s_j << P). By induction, if s_j is within d below the
    real value 2^(1/2^j)*2^P, then sqrt contracts the error to <= d/2 and
    the floor adds < 1, so every s_j lies in (true - 2, true].
  * Truncation to Q64.64 is entry = s_j >> (P - 64). It is proven
    unambiguous per entry by asserting
        (s_j >> (P-64)) == ((s_j + 4) >> (P-64)),
    i.e. no Q64.64 truncation boundary falls inside the error interval.
    If that assertion ever failed the script would abort; regenerate with
    a larger P. (It does not fail at P = 256.)
  * Independent exact cross-check for j <= 11 (m = 2^j <= 2048): the
    definition entry = floor(2^(1/m) * 2^64) is equivalent to the integer
    root bracketing  c^m <= 2^(64m+1) < (c+1)^m, verified with exact
    big-integer powers.
  * Fixed known values: entry_0 == isqrt(2^129) (floor(sqrt(2)*2^64)) and
    entry_63 == 2^64 exactly (2^64 * (2^(2^-64) - 1) = ln2 + eps < 1).

Usage:
    python tools/vector-generators/gen_exp2_table.py [--check]

--check verifies the emitted Rust file is byte-identical to a fresh
generation instead of writing it.
"""

from __future__ import annotations

import sys
from math import isqrt
from pathlib import Path

PRECISION = 256  # working fractional bits; 192 guard bits over Q64.64
ENTRIES = 64

REPO_ROOT = Path(__file__).resolve().parents[2]
RUST_OUT = REPO_ROOT / "crates" / "noos-ground" / "src" / "exp2_table.rs"


def exp2_table_entries(precision: int = PRECISION) -> list[int]:
    """The 64 exact Q64.64 entries floor(2^(2^-(k+1)) * 2^64), k = 0..63."""
    guard = precision - 64
    entries: list[int] = []
    s = isqrt(1 << (2 * precision + 1))  # floor(2^(1/2) * 2^P), exact
    for j in range(1, ENTRIES + 1):
        # s in (true - 2, true]; truncation must be boundary-free:
        if (s >> guard) != ((s + 4) >> guard):
            raise AssertionError(
                f"entry j={j}: Q64.64 truncation ambiguous at P={precision}; "
                "regenerate with higher precision"
            )
        entries.append(s >> guard)
        if j < ENTRIES:
            s = isqrt(s << precision)

    # Independent exact definition check for m = 2^j, j <= 11:
    # c = floor(2^(1/m) * 2^64)  <=>  c^m <= 2^(64m+1) < (c+1)^m.
    for j in range(1, 12):
        m = 1 << j
        c = entries[j - 1]
        bound = 1 << (64 * m + 1)
        assert c**m <= bound < (c + 1) ** m, f"exact root check failed at j={j}"

    # Fixed known values.
    assert entries[0] == isqrt(1 << 129), "entry_0 != floor(sqrt(2)*2^64)"
    assert entries[63] == 1 << 64, "entry_63 != 2^64"
    # Every entry is 65 bits or less and >= 2^64 (factor >= 1.0):
    assert all((1 << 64) <= e < (1 << 65) for e in entries)
    # Strictly decreasing toward 2^64:
    assert all(entries[i] > entries[i + 1] for i in range(ENTRIES - 1))
    return entries


def table_blake3_hex(entries: list[int]) -> str:
    """BLAKE3-256 of the 64 entries encoded as u128 little-endian (1024 B)."""
    import blake3

    blob = b"".join(e.to_bytes(16, "little") for e in entries)
    return blake3.blake3(blob).hexdigest()


def render_rust(entries: list[int]) -> str:
    lines = [
        "//! exp2_q64 version-1 constant table for Pulse (GENERATED FILE).",
        "//!",
        "//! GENERATED by `tools/vector-generators/gen_exp2_table.py` — DO NOT EDIT.",
        "//! Regenerate/verify with:",
        "//!     python tools/vector-generators/gen_exp2_table.py --check",
        "//!",
        "//! `EXP2_Q64_TABLE_V1[k] = floor(2^(2^-(k+1)) * 2^64)` for `k = 0..63`:",
        "//! the Q64.64 value of two raised to the k-th fractional-bit weight.",
        "//! Derivation and the exact rounding-order law are frozen in",
        "//! `protocol/spec/pulse-exp2-v1.md`. Table hash (BLAKE3-256 over the",
        f"//! 64 entries as u128 LE): `{table_blake3_hex(entries)}`.",
        "",
        "/// `floor(2^(2^-(k+1)) * 2^64)` for `k = 0..63`. Entry 0 is the weight",
        "/// of the most-significant fractional exponent bit (2^-1); entry 63",
        "/// (== 2^64 exactly) the least-significant (2^-64). Every entry is a",
        "/// 65-bit value in `[2^64, 2^65)`, so each multiply step is",
        "/// non-decreasing and the fractional product stays below `2 * T_a`.",
        "pub const EXP2_Q64_TABLE_V1: [u128; 64] = [",
    ]
    for k, e in enumerate(entries):
        lines.append(f"    0x{e:017x}, // k={k:2}: floor(2^(2^-{k + 1}) * 2^64)")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    entries = exp2_table_entries()
    rendered = render_rust(entries)
    if "--check" in argv:
        existing = RUST_OUT.read_text(encoding="utf-8")
        if existing != rendered:
            print(f"MISMATCH: {RUST_OUT} differs from fresh generation", file=sys.stderr)
            return 1
        print(f"OK: {RUST_OUT} matches fresh generation ({ENTRIES} entries)")
        return 0
    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {RUST_OUT} ({ENTRIES} entries, P={PRECISION})")
    print(f"table blake3 (u128 LE concat): {table_blake3_hex(entries)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
